### PR TITLE
Practitioner summary + Edit info

### PR DESCRIPTION
**Pull request by Sophia-bhs**

### CODE REVIEW

**Review by gazzyfire — COMMENTED** [review]
I get a notice warning:
Notice: session_start(): A session had already been started - ignoring in C:\Users\garyd\Documents\GitHub\BIOM9450_Project\footer.php on line 13

**Comment by Sophia-bhs** [comment]
> I get a notice warning: Notice: session_start(): A session had already been started - ignoring in C:\Users\garyd\Documents\GitHub\BIOM9450_Project\footer.php on line 13

How can I replicate this warning?

**Comment by gazzyfire** [comment]
> 

it occurs as soon as i log in

**Comment by Sophia-bhs** [comment]
> Notice: session_start(): A session had already been started

if(!isset($_SESSION)) { 
        session_start(); 
}
See what happens if you put this into footer - strangely it doesn't warn me when I log in..

**Comment by gazzyfire** [comment]
> > Notice: session_start(): A session had already been started
> 
> if(!isset($_SESSION)) { session_start(); } See what happens if you put this into footer - strangely it doesn't warn me when I log in..

i did that too and it doesnt come up with a warning anymore

**Review by z5256089 — COMMENTED** [review]
I think there's a problem with editing the patients, because the Value for the Gender currently is 'male' and 'female', not 'F' / 'M'. The value for the form should be changed. Line 103-104 of management.php.

**Comment by Sophia-bhs** [comment]
> I think there's a problem with editing the patients, because the Value for the Gender currently is 'male' and 'female', not 'F' / 'M'. The value for the form should be changed. Line 103-104 of management.php.

Changed management form values, please check if it stores the correct value into database~~

**Review by nisargkanthi — APPROVED** [review]

**Review by z5256089 — APPROVED** [review]

**Review by gazzyfire — APPROVED** [review]

**Pull request merged**
